version: "3.9"

services:
  app:
    build:
      dockerfile: ./Dockerfile
    ports:
      - "8000:80"
    environment:
      SQLALCHEMY_PG_CONN_URI: postgresql+psycopg2://user:pass@postgres/blog
    depends_on:
      postgres:
        condition: service_healthy
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: blog
    ports:
      - "5433:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
